### ISSUE TITLE
Design patterns resources

### ISSUE THREAD

**Issue by DilanLivera** [DilanLivera/notes#17]
## Description

It seems learning design patterns from multiple sources helps me understand them better. This note is a collection of resources to keep them in a centralised place.

## Scratch Notes

- [Null Object Pattern](https://github.com/DilanLivera/notes/issues/28)
- [Rules Engine Pattern](https://github.com/DilanLivera/courses/issues/5)
- [Proxy Pattern](https://github.com/DilanLivera/notes/issues/34)
- [Adapter Pattern](https://github.com/DilanLivera/notes/issues/35)
- [Facade Pattern](https://www.pmi.org/disciplined-agile/the-design-patterns-repository/the-facade-pattern)
- [Template Method Pattern](https://github.com/DilanLivera/notes/issues/36)
- [Decorator Pattern](https://github.com/DilanLivera/notes/issues/38)
- [Observer Pattern](https://docs.microsoft.com/dotnet/standard/events/observer-design-pattern)

## Resources

- [Design Patterns.pdf](https://github.com/DilanLivera/notes/files/11095306/Design.Patterns.pdf)
- [DevIQ - Design Patterns](https://deviq.com/design-patterns/design-patterns-overview)
- [Disciplined Agile - The Design Patterns Repository](https://www.pmi.org/disciplined-agile/the-design-patterns-repository)
- [Microsoft Docs - Cloud Design Patterns](https://docs.microsoft.com/azure/architecture/patterns/)
- [GitHub - skimedic/presentations: Patterns](https://github.com/skimedic/presentations/tree/master/Patterns/Current)
- [Pluralsight - Design Patterns Library by David Starr, Niraj Bhatt, Robert Horvick, Scott Allen, Brian Lagunas, Steve Smith, Donald Belcham, John Sonmez, John Brown, Keith Sparkjoy, and Glenn Block](https://www.pluralsight.com/courses/patterns-library)

**Comment by DilanWaduge** [comment]
This note is moved [here](https://gist.github.com/DilanLivera/e6755b9140895c23526385696d369b05).
