### ISSUE TITLE
Postman - Tips and Tricks

### ISSUE THREAD

**Issue by DilanLivera** [DilanLivera/notes#20]
## Description

A list of resources and helpful tips and tricks to use with Postman requests.

## Scratch Notes

- Request parameters and headers could be added/edited using the bulk edit feature.

- Set request date header value as UTC date.

  ```javascript
  const utcDate = new Date().toUTCString();
  
  pm.request.headers.add({ key: "Date", value: utcDate});
  ```

## Resources

- [Postman Learning Center - Dynamic variables](https://learning.postman.com/docs/writing-scripts/script-references/variables-list/)
- [Postman Learning Center - Scripting in Postman](https://learning.postman.com/docs/writing-scripts/intro-to-scripts/)

**Comment by DilanWaduge** [comment]
This note is moved to [here](https://gist.github.com/DilanLivera/daf65aec2f7dce6451f7113bb44bd298).
