### ISSUE TITLE
API mocking tools

### ISSUE THREAD

**Issue by DilanLivera** [DilanLivera/notes#27]
## Description

A list of resources for API mocking tools.

## Scratch Notes

- Some people suggested [Pact](https://docs.pact.io/) for API mocking. But it seems, Pact is a contract testing tool. According to [Pact docs](https://docs.pact.io/),

  > Pact is a code-first tool for testing HTTP and message integrations using contract tests. Contract tests assert that inter-application messages conform to a shared understanding that is documented in a contract. Without contract testing, the only way to ensure that applications will work correctly together is by using expensive and brittle integration tests.

## Resources

- [Stoplight - Prism](https://stoplight.io/open-source/prism/)
- [Mock Service Worker](https://mswjs.io/)
- [GitHub - JSON Server](https://github.com/typicode/json-server)
- [Mirage - Mirage JS](https://miragejs.com/)
- [Broadcom - Service Virtualization](https://www.broadcom.com/products/software/continuous-testing/service-virtualization)
- [Microfocus - Service Virtualization](https://www.microfocus.com/en-us/products/service-virtualization/overview)

**Comment by DilanWaduge** [comment]
This note is moved [here](https://gist.github.com/DilanLivera/79026f3723a24bc576a568e86eb22979).
