### ISSUE TITLE
Mocking HTTP APIs with Prism

### ISSUE THREAD

**Issue by DilanLivera** [DilanLivera/notes#32]
## Description

This note is about HTTP API mocking with Prism. The following is from [Prism Docs: Overview](https://meta.stoplight.io/docs/prism/ZG9jOjYx-overview), which describe what Prism does

> Prism is a best in class Mock Server and Validation Proxy for OpenAPI documents and Postman Collections.

### How to install

There are a few ways to install Prism. Prism docs include a detailed explanation of the process, which you can find at [Prism Docs: Installation](https://meta.stoplight.io/docs/prism/ZG9jOjky-installation).

### Mock an API document with Prism CLI

Prism CLI has two commands. One is `mock`, and the other is `proxy`. According to [Prism Docs: Prism CLI: Proxy](https://meta.stoplight.io/docs/prism/ZG9jOjk0-prism-cli#proxy), `proxy` command

> creates an HTTP server that will proxy all the requests to the specified upstream server. Prism will analyze the request coming in and the response coming back from the upstream server and report the discrepancies with what's declared in the provided OpenAPI document.

We need to use the `mock` command to mock an API document.

```powershell
#using a hosted api document
prism mock https://raw.githack.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore-expanded.yaml

#using an api document in local machine
prism mock C:\apis\petstore.oas2.yaml
```

We can use the following parameters with the `prism mock` command:

| Parameter              | Description                                                                                   | Type                                       |
| ---------------------- | --------------------------------------------------------------------------------------------- | ------------------------------------------ |
| `--version`            | Show version number                                                                           | [boolean]                                  |
| `--help`               | Show help                                                                                     | [boolean]                                  |
| `-p`, `--port`         | Port that Prism will run on                                                                   | [number] [required] [default: 4010]        |
| `-h`, `--host`         | Host that Prism will listen to                                                                | [string] [required] [default: "127.0.0.1"] |
| `--cors`               | Enables CORS headers                                                                          | [boolean] [default: true]                  |
| `-m`, `--multiprocess` | Forks the http server from the CLI for faster log processing                                  | [boolean] [default: false]                 |
| `--errors`             | Specifies whether request/response violations marked as errors will produce an error response | [boolean] [required] [default: false]      |
| `-d`, `--dynamic`      | Dynamically generate examples                                                                 | [boolean] [default: false]                 |

After starting the mock server you can call the path in the API document by appending the path to the `http://localhost.4010` base URL(e.g. `http://localhost.4010/api/v3/store/order/123`), assuming you used the default host and port. The mock server will return the `200 OK` response if the request is valid.

### Retrieve an example for an endpoint

According to [Prism Docs: HTTP Mocking: Response Generation](https://meta.stoplight.io/docs/prism/ZG9jOjk1-http-mocking#response-generation)

> Prism will try to return meaningful responses based on whatever information it has available, like response examples, and use various fallback mechanisms in case no examples were provided. This means any OpenAPI description document can be used with no extra work, but better documents provide better results.

To get a specific response example from the API document, we can use the `Prefer` header parameter with the example value.

![postman request with the prefer header for getting an example in the api document](https://user-images.githubusercontent.com/35996237/163495870-6e6f5843-b8cf-4b65-a95c-930da6d75d63.png)

### Dynamic response generation

For Prism to return dynamic responses for the request, we need to add the `prefer` header with the `dynamic=true` value.

![postman request with a dynamic response](https://user-images.githubusercontent.com/35996237/161036667-e74a3cb1-b652-48d3-9e33-3185aec04d56.png)

Please find more info at [Prism Docs: HTTP Mocking: Response Generation: Static or Dynamic Generation](https://meta.stoplight.io/docs/prism/ZG9jOjk1-http-mocking#static-or-dynamic-generation).

### Request Validation

We can use the `--errors` parameter to retrieve any validation errors in the request. If there are any validation errors, Prism mock will,

- return `400 Bad Request` response if the `path` contains a `400` response. During my testing of this functionality, I also saw a header named `sl-violations` in the response with an array of errors similar to the following.

  ```json
  [
    {
      "location": ["request", "body"],
      "severity": "Error",
      "code": "required",
      "message": "must have required property 'name'"
    }
  ]
  ```

  ![prism log for the bad request](https://user-images.githubusercontent.com/35996237/161197698-572a9935-2656-4f42-a3c9-c94c315444a8.png)

- return the `422 Unprocessable Entity` response if the `path` does not contain a `400` response. The response will contain information about the error/s in the response body. E.g.

  ```json
  {
    "type": "https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY",
    "title": "Invalid request",
    "status": 422,
    "detail": "Your request is not valid and no HTTP validation response was found in the spec, so Prism is generating this error for you.",
    "validation": [
      {
        "location": ["body"],
        "severity": "Error",
        "code": "required",
        "message": "must have required property 'name'"
      }
    ]
  }
  ```

  ![prism log for the bad request](https://user-images.githubusercontent.com/35996237/161197996-53d8b9f6-5ea6-46b3-865a-e79d839417a6.png)

**_Note:_** During my local testing I was getting the same behaviour as above for validation errors with or without the `--errors` parameter.

Please refer to [Prism Docs: Errors](https://meta.stoplight.io/docs/prism/ZG9jOjE2MDY1NjY5-errors) page to find more information about the errors(e.g. `UNPROCESSABLE_ENTITY`, `NO_BASE_URL_ERROR`) Prism returns.

Please find more info at [Prism Docs: Request Validation](https://meta.stoplight.io/docs/prism/ZG9jOjk2-request-validation).

### Mocking Callbacks with Prism

Please find more info at [Prism Docs: Mocking Callbacks with Prism](https://meta.stoplight.io/docs/prism/ZG9jOjk4-mocking-callbacks-with-prism).

## Resources

- [Prism Docs](https://meta.stoplight.io/docs/prism)
- [Swagger Petstore - OpenAPI 3.0](https://petstore3.swagger.io/)

**Comment by DilanWaduge** [comment]
This note is moved [here](https://gist.github.com/DilanLivera/79026f3723a24bc576a568e86eb22979).
