### ISSUE TITLE
Proxy Pattern

### ISSUE THREAD

**Issue by DilanLivera** [DilanLivera/notes#34]
## Description

This note is about the Proxy design pattern.

### Problem

Need to control access to a type for performance, security, and other reasons.

Example

The following is from [C# Design Patterns: Proxy](https://www.pluralsight.com/courses/c-sharp-design-patterns-proxy) course.

```mermaid
sequenceDiagram
    participant Client
    participant Proxy
    participant Real Service
    Client->>Proxy: SomeMethod()
    activate Proxy
    Proxy->>Real Service: SomeMethod()
    activate Real Service
    Real Service-->>Proxy: SomeMethod() response
    deactivate Real Service
    Proxy-->>Client: SomeMethod() response
    deactivate Proxy
```

Typically proxy will mirror the interface of the real service. When the client makes a request to the proxy, the proxy has an opportunity to perform any logic needed before forwarding the request to the real service and, after receiving the response, before returning the response to the client (Eg. Caching the response if it is acting as a Cache).

![proxy structure](https://user-images.githubusercontent.com/35996237/163741301-4cc5c91d-694d-418a-a495-4d6f40e89f3b.png)

#### Virtual Proxy

> A virtual proxy is a stand-in for an object that is expensive to create for real. Its purpose is generally to optimize for performance. Instead of being the real object, the proxy knows how to get the real object when required, after which it delegates all calls back to that real object. Two common examples of this approach are placeholders within UI screens to allow the screen to render quickly, even if real data isn't yet available. And lazy‑loaded entity properties, which are only populated if the property is accessed or perhaps when it is first enumerated. - _Steve Smith, "C# Design Patterns: Proxy"_

Please find the code samples from _**C# Design Patterns: Proxy**_ course at [ardalis/DesignPatternsInCSharp: Proxy: Virtual Proxy](https://github.com/ardalis/DesignPatternsInCSharp/tree/master/DesignPatternsInCSharp/Proxy/VirtualProxy).

#### Remote Proxy

Remote Proxy is used to hide the details of working with remote data or services.

> The goal of a remote proxy is to act as a local resource while hiding the details of how to connect to a remote resource over a network. The remote proxy centralises all knowledge of the network details, and often these proxies can be generated automatically based on some service definition file, like WSDL, .proto, a Swagger, or open API specification. - _Steve Smith, "C# Design Patterns: Proxy"_

Please find the code samples from _**C# Design Patterns: Proxy**_ course at [ardalis/DesignPatternsInCSharp: Proxy: Remote Proxy](https://github.com/ardalis/DesignPatternsInCSharp/tree/master/DesignPatternsInCSharp/Proxy/RemoteProxy).

#### Smart Proxy

Smart Proxy performs additional actions when a resource is accessed.

> A smart proxy is used to add additional logic around access to a resource. These can be useful to perform resource counting, or to manage the caching of a resource, or to lock access to shared resources. - _Steve Smith, "C# Design Patterns: Proxy"_

Please find the code samples from _**C# Design Patterns: Proxy**_ course at [ardalis/DesignPatternsInCSharp: Proxy: Smart Proxy](https://github.com/ardalis/DesignPatternsInCSharp/tree/master/DesignPatternsInCSharp/Proxy/SmartProxy).

#### Protective Proxy

Protective Proxy controls access to a sensitive resource by checking whether or not the client is authorised to perform those operations.

> A protective or protection proxy is used to control access to a resource based on certain rules. This can help to eliminate having these checks live either in the client code or in the resource itself. Generally, this helps with separation of concerns, the don't repeat yourself principle, and the single responsibility principle. You can think of the protective proxy as being a kind of gatekeeper around the resource. - _Steve Smith, "C# Design Patterns: Proxy"_

Please find the code samples from _**C# Design Patterns: Proxy**_ course at [ardalis/DesignPatternsInCSharp: Proxy: Protective Proxy](https://github.com/ardalis/DesignPatternsInCSharp/tree/master/DesignPatternsInCSharp/Proxy/ProtectiveProxy).

### Related Patterns

- The Decorator pattern has a very similar structure, but the Decorator pattern intends to add functionality, whereas the Proxy intends to control access. In the case of a Smart Proxy, this difference is very slim.
- The Prototype and the Proxy could be used to deal with an expensive object to create. Typically, a virtual proxy is used for this. However, the Proxy offers a stub or placeholder and fetches the real object on demand, while the Prototype pattern keeps a copy of the object on hand and can clone it when required.
- The Adapter is structurally very similar to the Proxy, but its purpose is to convert an incompatible interface into one that works for the client. It's not concerned with access control.
- The Flyweight pattern is also very similar to the Proxy pattern. However, the Flyweight pattern is designed to manage many references to a shared instance, while the Proxy is designed to wrap a single specific instance.

## Resources

- [Pluralsight - C# Design Patterns: Proxy by Steve Smith](https://www.pluralsight.com/courses/c-sharp-design-patterns-proxy)
- [GitHub - ardalis/DesignPatternsInCSharp: Proxy](https://github.com/ardalis/DesignPatternsInCSharp/tree/master/DesignPatternsInCSharp/Proxy)

**Comment by DilanWaduge** [comment]
This note is moved [here](https://gist.github.com/DilanLivera/e6755b9140895c23526385696d369b05).
