### ISSUE TITLE
Adapter Pattern

### ISSUE THREAD

**Issue by DilanLivera** [DilanLivera/notes#35]
## Description

This note is about the Adapter design pattern.

### Problem

Incompatible interfaces between a client and a service provider. 

Adapters convert the interface of one class into an interface a client expects.

### Two Kinds of Adapters

![characteristics of object and class adapters](https://user-images.githubusercontent.com/35996237/163763919-07080da9-5258-427d-8b2a-ac287f31ed6f.png)

> One variation of class adapter that doesn't require multiple class inheritance simply implements the adapter interface. This variation can be used in languages like C# and Java. In C#, you'll mostly use object adapters. The reason is that C# doesn't support multiple inheritances, and a design principle of C# is to prefer composition over inheritance. - _Steve Smith, "C# Design Patterns: Adapter"_

![object adapter class relationship](https://user-images.githubusercontent.com/35996237/163765751-7792251d-c887-4acd-a243-bb22293eea1e.png)

Please find the code samples from _**C# Design Patterns: Adapter**_ course at [ardalis/DesignPatternsInCSharp: Adapter](https://github.com/ardalis/DesignPatternsInCSharp/tree/master/DesignPatternsInCSharp/Adapter).

### Related Patterns

- The Decorator has a similar structure, but the decorator intends to add functionality.
- The Bridge pattern is very similar in structure, but its intent specifically is to allow interfaces and their implementations to vary independently from one another.
- The Proxy is structurally similar as well, but it intends to control access to a resource, not to convert an incompatible interface.
- The Repository pattern sometimes acts as an adapter, providing a common interface for persistence that can map various incompatible interfaces to a single common data access strategy.
- The Strategy pattern is frequently used with the Adapter pattern to inject different implementations of behaviour into a particular client class.
The Facade design pattern's intent is similar to the adapters in that it alters an interface to make it easier for a client to use. The difference, though, is that the facade often sits in front of multiple different types. Its goal is to simplify a complex set of operations, not necessarily to provide a way to swap between different incompatible operations easily.

### Adapter for Results

> The adapter pattern can also be applied to result types, not just the service providers. In this case, to apply the pattern, you must create or choose a common result type that your client expects to consume. Then you can inherit from this type and use composition to delegate calls made to the common type to the specific incompatible type. - _Steve Smith, "C# Design Patterns: Adapter"_

Please find a code samples of this at [ardalis/DesignPatternsInCSharp: Adapter: ResultWrapper](https://github.com/ardalis/DesignPatternsInCSharp/tree/master/DesignPatternsInCSharp/Adapter/06_ResultWrapper).

## Resources

- [Pluralsight - C# Design Patterns: Adapter by Steve Smith](https://www.pluralsight.com/courses/c-sharp-design-patterns-adapter)

**Comment by DilanWaduge** [comment]
This note is moved [here](https://gist.github.com/DilanLivera/e6755b9140895c23526385696d369b05).
