### ISSUE TITLE
Template Method Pattern

### ISSUE THREAD

**Issue by DilanLivera** [DilanLivera/notes#36]
## Description

This note is about the Template Method design pattern.

### What is Template Method?

> A template method is a method in a superclass that defines the skeleton of an operation in terms of higher-level steps. Subclass implement these steps. - _Steve Smith, "C# Design Patterns: Template Method"_

![Template Method class diagram from "C# Design Patterns: Template Method by Steve Smith" Pluralsight course](https://user-images.githubusercontent.com/35996237/167767977-4ba7fd54-ed3f-4f3b-910b-4db7df9a0930.png)

### When to use Template Method?

- Lockdown a process while allowing clients to alter certain steps in the process
- Generalize duplicate behaviour among methods in several classes
- Create and control extension points for future code implementations
- Very simple cases where you want to use inheritance, but you need to ensure base functionality is preserved. By default, child types can override virtual members of base types. When they do, the new method is called instead of the original. If the original method needs to be called and if it specifically must be called either before or after the child type's additional behaviour, there's no built‑in way to enforce this behaviour.

Please find the code samples from C# Design Patterns:  Template Method course at [ardalis/DesignPatternsInCSharp: Template Method](https://github.com/ardalis/DesignPatternsInCSharp/tree/master/DesignPatternsInCSharp/TemplateMethod).

### Related Patterns

- The Factory Method is often called by the template method. Frequently, the result of the template method is a returned object and part of the process of producing that object may be to invoke an appropriate factory method, perhaps in addition to other steps.
- The Strategy pattern provides a way to vary an entire algorithm used by a class by delegating it to another class via composition. The Template Method encapsulates an algorithm but allows it to vary among its child classes through inheritance.
- The Rules Engine pattern frequently leverages the Template Method pattern in its implementation. Individual rule processing may follow a process defined in a base rule class. Similarly, the engine itself may inherit behaviour from a base rule engine class that defines how it should operate.

## Resources

- [Pluralsight - C# Design Patterns: Template Method by Steve Smith](https://www.pluralsight.com/courses/c-sharp-design-patterns-template-method)

**Comment by DilanWaduge** [comment]
This note is moved [here](https://gist.github.com/DilanLivera/e6755b9140895c23526385696d369b05).
