### ISSUE TITLE
Decorator Pattern

### ISSUE THREAD

**Issue by DilanLivera** [DilanLivera/notes#38]
## Description

This note is about the Decorator design pattern.

## Scratch Notes

Any notes which are taken during research

## Resources

- [Pluralsight - Design Patterns Library by David Starr, Niraj Bhatt, Robert Horvick, Scott Allen, Brian Lagunas, Steve Smith, Donald Belcham, John Sonmez, John Brown, Keith Sparkjoy, and Glenn Block: Decorator Design Pattern](https://app.pluralsight.com/course-player?clipId=95369b34-a1f2-4196-a8c1-5c6f4bd4b380)
- [Pluralsight - Dependency Injection in ASP.NET Core 6 by Steve Gordon: Applying the Decorator Pattern with Scrutor](https://app.pluralsight.com/course-player?clipId=0510a006-6ce2-405c-97d6-4dd73409ad03)

**Comment by DilanWaduge** [comment]
This note is moved [here](https://gist.github.com/DilanLivera/e6755b9140895c23526385696d369b05).
