### ISSUE TITLE
Kibana Visualizations

### ISSUE THREAD

**Issue by DilanWaduge** [DilanLivera/notes#59]
## Description

This note is about how to create data visualizations in Kibana.

### Data Table

[How to Create a Data Table with Kibana Lens](https://www.youtube.com/watch?v=NRDue0dVBQI)

**Comment by DilanLivera** [comment]
I have moved this note to [Kibana Visualizations](https://gist.github.com/DilanLivera/f82a6d3a893ef1a081583e4bcc4d1953) GitHub gist.
